package app.pluct.ui.screens

import android.content.Intent
import android.widget.Toast
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.ClipboardManager
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.unit.dp
import app.pluct.data.entity.VideoItem

/**
 * Pluct-UI-Screen-VideoDetail-03Content - Simplified Video Details content
 * Follows naming convention: [Project]-[ParentScope]-[ChildScope]-[Separation of Concern][CoreResponsibility]
 * Redesigned for simplicity: Sticky actions, clean layout, hidden technical details
 */
@Composable
fun PluctVideoDetailContent(
    video: VideoItem,
    onUpgradeClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val clipboardManager: ClipboardManager = LocalClipboardManager.current
    val context = LocalContext.current

    Column(
        modifier = modifier.fillMaxSize()
    ) {
        PluctVideoDetailActionBar(
            onCopy = {
                video.transcript?.let { transcript ->
                    clipboardManager.setText(AnnotatedString(transcript))
                    Toast.makeText(context, "Transcript copied to clipboard", Toast.LENGTH_SHORT).show()
                }
            },
            onShare = {
                val shareText = buildString {
                    appendLine(getVideoDetailDisplayTitle(video))
                    val author = getVideoDetailDisplayAuthor(video)
                    if (author.isNotBlank()) appendLine(author)
                    appendLine(video.url)
                    appendLine()
                    appendLine("Transcript:")
                    appendLine(video.transcript ?: "No transcript available")
                    appendLine()
                    appendLine("Generated by Pluct")
                }
                val shareIntent = Intent().apply {
                    action = Intent.ACTION_SEND
                    putExtra(Intent.EXTRA_TEXT, shareText)
                    type = "text/plain"
                }
                context.startActivity(Intent.createChooser(shareIntent, "Share transcript"))
            },
            onExport = {
                val exportText = buildString {
                    appendLine("Title: ${getVideoDetailDisplayTitle(video)}")
                    val author = getVideoDetailDisplayAuthor(video)
                    if (author.isNotBlank()) appendLine("Author: ${author.removePrefix("by ")}")
                    appendLine("URL: ${video.url}")
                    appendLine()
                    appendLine("Transcript:")
                    appendLine(video.transcript ?: "No transcript available")
                }
                val shareIntent = Intent().apply {
                    action = Intent.ACTION_SEND
                    putExtra(Intent.EXTRA_TEXT, exportText)
                    type = "text/plain"
                }
                context.startActivity(Intent.createChooser(shareIntent, "Export transcript"))
            }
        )

        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(top = 4.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            item {
                PluctVideoDetailHeader(video = video)
            }

            item {
                PluctVideoDetailTranscript(video = video)
            }

            item {
                PluctVideoDetailAdvancedSection(video = video)
            }

            item {
                Spacer(modifier = Modifier.height(16.dp))
            }
        }
    }
}
