package app.pluct.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.ClipboardManager
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.unit.dp
import app.pluct.data.entity.VideoItem
import android.content.Intent
import android.widget.Toast

/**
 * Pluct-UI-Screen-VideoDetail-03Content - Simplified Video Details content
 * Follows naming convention: [Project]-[ParentScope]-[ChildScope]-[Separation of Concern][CoreResponsibility]
 * Redesigned for simplicity: Sticky actions, clean layout, hidden technical details
 */
@Composable
fun PluctVideoDetailContent(
    video: VideoItem,
    onUpgradeClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    val clipboardManager: ClipboardManager = LocalClipboardManager.current
    val context = LocalContext.current
    
    Column(
        modifier = modifier.fillMaxSize()
    ) {
        // Sticky Action Bar (always visible at top)
        PluctVideoDetailActionBar(
            onCopy = {
                // Copy transcript to clipboard
                video.transcript?.let { transcript ->
                    clipboardManager.setText(AnnotatedString(transcript))
                    Toast.makeText(context, "Transcript copied to clipboard", Toast.LENGTH_SHORT).show()
                }
            },
            onShare = {
                // Enhanced share with metadata
                val shareText = buildString {
                    appendLine("📹 ${video.title}")
                    if (video.author.isNotBlank()) appendLine("👤 by ${video.author}")
                    appendLine("🔗 ${video.url}")
                    appendLine()
                    appendLine("📝 Transcript:")
                    appendLine(video.transcript ?: "No transcript available")
                    appendLine()
                    appendLine("Generated by Pluct")
                }
                val shareIntent = Intent().apply {
                    action = Intent.ACTION_SEND
                    putExtra(Intent.EXTRA_TEXT, shareText)
                    type = "text/plain"
                }
                context.startActivity(Intent.createChooser(shareIntent, "Share transcript"))
            },
            onExport = {
                // Export to TXT
                val exportText = buildString {
                    appendLine("Title: ${video.title}")
                    if (video.author.isNotBlank()) appendLine("Author: ${video.author}")
                    appendLine("URL: ${video.url}")
                    appendLine()
                    appendLine("Transcript:")
                    appendLine(video.transcript ?: "No transcript available")
                }
                val shareIntent = Intent().apply {
                    action = Intent.ACTION_SEND
                    putExtra(Intent.EXTRA_TEXT, exportText)
                    type = "text/plain"
                }
                context.startActivity(Intent.createChooser(shareIntent, "Export transcript"))
            }
        )
        
        // Scrollable Content
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(top = 8.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Header: Title, Author, Offline Badge
            item {
                PluctVideoDetailHeader(video = video)
            }
            
            // Transcript (main content)
            item {
                PluctVideoDetailTranscript(video = video)
            }
            
            // Advanced Details (collapsible, hidden by default)
            item {
                PluctVideoDetailAdvancedSection(video = video)
            }
            
            // Bottom spacing
            item {
                Spacer(modifier = Modifier.height(16.dp))
            }
        }
    }
}
